Metrics/LineLength:
  Max: 95
  IgnoredPatterns:
    - '^ *#.*$'

Naming/UncommunicativeMethodParamName:
  AllowedNames: io, id, to, by, on, in, at, fk, pk

Style/LambdaCall:
  Enabled: false

Naming/ConstantName:
  Exclude:
    - 'lib/entity_schema.rb'

Metrics/BlockLength:
  Exclude:
    - 'entity_schema.gemspec'

Metrics/AbcSize:
  Exclude:
    - 'lib/entity_schema/setup_field.rb'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'lib/entity_schema.rb'
    - 'lib/entity_schema/transformers/*'
